class FlyerScreen extends Screen
  anchor: -> $('navigationBar[name=CreateFlyer]')

  constructor: ->
    super 'flyer'

    extend @elements,
    'Back' : -> view.navigationBars()[0].buttons()[0],
    'Help' : -> view.navigationBars()[0].buttons()[1],
    'Next / Delete / Undo' : -> view.navigationBars()[0].buttons()[2],
    'Done / Share' : -> view.navigationBars()[0].buttons()[3],
    'Text' : -> $('#Text'),
    'Photo' : -> $('#Photo'),
    'Symbols' : -> $('#Symbols'),
    'Clipart' : -> $('#Clipart'),
    'Background' : -> $('#Background'),
    'Text input' : ->$("#TextInput"),
    'Font' : -> $('#Font'),
    'Color' : -> $('#Color'),
    'Size' : -> $('#Size'),
    'Text border' : -> $('#TextBorder'),
    'Edit' : -> $('#Edit'),
    'Camera' : -> $('#Camera'),
    'Gallery' : -> $('#Gallery'),
    'Width' : -> $('#Width'),
    'Height' : -> $('#Height'),
    'Library' : -> $('#Library'),
    'Take a photo' : -> $('#TakePhoto'),
    'Cameral roll' : -> $('#CameraRoll'),
    'Border' : -> $('#Border'),
    'Facebook Button' : -> $('#Facebook'),
    'Twitter Button' : -> $('#Twitter'),
    'Tumblr Button' : -> $('#Tumblr'),
    'Instagram Button' : -> $('#Instagram'),
    'Flicker Button' : -> $('#Flicker'),
    'Email Button' : -> $('#Email'),
    'SMS Button' : -> $('#SMS'),
    'Copy Button' : -> $('#Copy'),
    'Tile1' : -> view.scrollViews()[0].buttons()[0],
    'Tile2' : -> view.scrollViews()[0].buttons()[1],
    'Tile3' : -> view.scrollViews()[0].buttons()[2],
    'Tile4' : -> view.scrollViews()[0].buttons()[3],
    'Tile5' : -> view.scrollViews()[0].buttons()[4],
    'Tile6' : -> view.scrollViews()[0].buttons()[5],
    'Tile7' : -> view.scrollViews()[0].buttons()[6],
    'Tile8' : -> view.scrollViews()[0].buttons()[7],
    'Tile9' : -> view.scrollViews()[0].buttons()[8],
    'Tile10' : -> view.scrollViews()[0].buttons()[9],
    'Tile11' : -> view.scrollViews()[0].buttons()[10],
    'Tile12' : -> view.scrollViews()[0].buttons()[11],
    'Tile13' : -> view.scrollViews()[0].buttons()[12],
    'Tile14' : -> view.scrollViews()[0].buttons()[13],
    'Tile15' : -> view.scrollViews()[0].buttons()[14],
    'Tile16' : -> view.scrollViews()[0].buttons()[15],
    'Tile17' : -> view.scrollViews()[0].buttons()[16],
    'Tile18' : -> view.scrollViews()[0].buttons()[17],
    'Tile19' : -> view.scrollViews()[0].buttons()[18],
    'Tile20' : -> view.scrollViews()[0].buttons()[19],
    'Tile21' : -> view.scrollViews()[0].buttons()[20],
    'Tile22' : -> view.scrollViews()[0].buttons()[21],
    'Tile23' : -> view.scrollViews()[0].buttons()[22],
    'Tile24' : -> view.scrollViews()[0].buttons()[23],
    'Tile25' : -> view.scrollViews()[0].buttons()[24]