class FlyerScreen extends Screen
  anchor: -> $('navigationBar[name=CreateFlyer]')

  constructor: ->
    super 'flyer'

    extend @elements,
    'Back' : -> view.navigationBars()[0].buttons()[0],
    'Help' : -> view.navigationBars()[0].buttons()[1],
    'Next' : -> view.navigationBars()[0].buttons()[2],
    'Done' : -> view.navigationBars()[0].buttons()[2],
	'Undo' : -> view.navigationBars()[0].buttons()[2],
    'Share' : -> view.navigationBars()[0].buttons()[3],
    'Text' : -> $('#Text'),
    'Photo' : -> $('#Photo'),
    'Symbols' : -> $('#Symbols'),
    'Clipart' : -> $('#Clipart'),
    'Background' : -> $('#Background'),
    'Text input' : -> $('#TextInput'),
    'Font' : -> $('#Font'),
    'Color' : -> $('#Color'),
    'Size' : -> $('#Size'),
    'Text border' : -> $('#TextBorder'),
    'Edit' : -> $('#Edit'),
    'Camera' : -> $('#Camera'),
    'Gallery' : -> $('#Gallery'),
    'Width' : -> $('#Width'),
    'Height' : -> $('#Height'),
    'Library' : -> $('#Library'),
    'Take a photo' : -> $('#TakePhoto'),
    'Cameral roll' : -> $('#CameraRoll'),
    'Border' : -> $('#Border'),
    'Tile1' : -> $('#Scrollview').views()[0],
    'Tile2' : -> $('#Scrollview').views()[1],
    'Tile3' : -> $('#Scrollview').views()[2],
    'Tile4' : -> $('#Scrollview').views()[3],
    'Tile5' : -> $('#Scrollview').views()[4],
    'Tile6' : -> $('#Scrollview').views()[5],
    'Tile7' : -> $('#Scrollview').views()[6],
    'Tile8' : -> $('#Scrollview').views()[7],
    'Tile9' : -> $('#Scrollview').views()[8],
    'Tile10' : -> $('#Scrollview').views()[9],
    'Tile11' : -> $('#Scrollview').views()[10],
    'Tile12' : -> $('#Scrollview').views()[11],
    'Tile13' : -> $('#Scrollview').views()[12],
    'Tile14' : -> $('#Scrollview').views()[13],
    'Tile15' : -> $('#Scrollview').views()[14],
    'Tile15' : -> $('#Scrollview').views()[15],
    'Tile17' : -> $('#Scrollview').views()[16],
    'Tile18' : -> $('#Scrollview').views()[17],
    'Tile19' : -> $('#Scrollview').views()[18],
    'Tile20' : -> $('#Scrollview').views()[19],
    'Tile21' : -> $('#Scrollview').views()[20],
    'Tile22' : -> $('#Scrollview').views()[21],
    'Tile23' : -> $('#Scrollview').views()[22],
    'Tile24' : -> $('#Scrollview').views()[23],
    'Tile25' : -> $('#Scrollview').views()[24]