//
//  Colors.swift
//  GifFactoryApp
//
//  DESCRIPTION:
//      Collection of color constants.
//
//  Created by Storix.
//  Copyright © 2016 Storix. All rights reserved.
//

import Foundation

/**
 *  Struct with color names in accordance with their hex codes.
 *  All modern browsers support the following color names (see http://www.w3schools.com/colors/colors_names.asp)
 *
 *  You can create colors like this: 
    ```
    UIColor.sh_colorFromHexCode(Colors.ORANGERED)
    ```
 *
 */
struct Colors {
  static let GREY_1:  String = "0x111111"
  static let GREY_2:  String = "0x222222"
  static let GREY_3:  String = "0x333333"
  static let GREY_4:  String = "0x444444"
  static let GREY_5:  String = "0x555555"
  static let GREY_6:  String = "0x666666"
  static let GREY_7:  String = "0x777777"
  static let GREY_8:  String = "0x888888"
  static let GREY_9:  String = "0x999999"
  static let WHITE_1:  String = "0xf9f9f9"
  static let WHITE_2:  String = "0xf3f3f3"
  static let WHITE_3:  String = "0xfafafa"
  static let WHITE_4:  String = "0xf6f6f6"
  static let WHITE_5:  String = "0xe6e6e6"
  static let WHITE_6:  String = "0xeeeeee"
  static let WHITE_7:  String = "0xe8e8e8"
  static let WHITE_8:  String = "0xe2e2e2"
  static let WHITE_9:  String = "0xE4E4E4"
  static let ALICEBLUE:  String = "0xF0F8FF"
  static let ANTIQUEWHITE:  String = "0xFAEBD7"
  static let AQUA:  String = "0x00FFFF"
  static let AQUAMARINE:  String = "0x7FFFD4"
  static let AZURE:  String = "0xF0FFFF"
  static let BEIGE:  String = "0xF5F5DC"
  static let BISQUE:  String = "0xFFE4C4"
  static let BLACK:  String = "0x000000"
  static let BLANCHEDALMOND:  String = "0xFFEBCD"
  static let BLUE:  String = "0x0000FF"
  static let BLUEVIOLET:  String = "0x8A2BE2"
  static let BROWN:  String = "0xA52A2A"
  static let BURLYWOOD:  String = "0xDEB887"
  static let CADETBLUE:  String = "0x5F9EA0"
  static let CHARTREUSE:  String = "0x7FFF00"
  static let CHOCOLATE:  String = "0xD2691E"
  static let CORAL:  String = "0xFF7F50"
  static let CORNFLOWERBLUE:  String = "0x6495ED"
  static let CORNSILK:  String = "0xFFF8DC"
  static let CRIMSON:  String = "0xDC143C"
  static let CYAN:  String = "0x00FFFF"
  static let DARKBLUE:  String = "0x00008B"
  static let DARKCYAN:  String = "0x008B8B"
  static let DARKGOLDENROD:  String = "0xB8860B"
  static let DARKGRAY:  String = "0xA9A9A9"
  static let DARKGREY:  String = "0xA9A9A9"
  static let DARKGREEN:  String = "0x006400"
  static let DARKKHAKI:  String = "0xBDB76B"
  static let DARKMAGENTA:  String = "0x8B008B"
  static let DARKOLIVEGREEN:  String = "0x556B2F"
  static let DARKORANGE:  String = "0xFF8C00"
  static let DARKORCHID:  String = "0x9932CC"
  static let DARKRED:  String = "0x8B0000"
  static let DARKSALMON:  String = "0xE9967A"
  static let DARKSEAGREEN:  String = "0x8FBC8F"
  static let DARKSLATEBLUE:  String = "0x483D8B"
  static let DARKSLATEGRAY:  String = "0x2F4F4F"
  static let DARKSLATEGREY:  String = "0x2F4F4F"
  static let DARKTURQUOISE:  String = "0x00CED1"
  static let DARKVIOLET:  String = "0x9400D3"
  static let DEEPPINK:  String = "0xFF1493"
  static let DEEPSKYBLUE:  String = "0x00BFFF"
  static let DIMGRAY:  String = "0x696969"
  static let DIMGREY:  String = "0x696969"
  static let DODGERBLUE:  String = "0x1E90FF"
  static let FIREBRICK:  String = "0xB22222"
  static let FLORALWHITE:  String = "0xFFFAF0"
  static let FORESTGREEN:  String = "0x228B22"
  static let FUCHSIA:  String = "0xFF00FF"
  static let GAINSBORO:  String = "0xDCDCDC"
  static let GHOSTWHITE:  String = "0xF8F8FF"
  static let GOLD:  String = "0xFFD700"
  static let GOLDENROD:  String = "0xDAA520"
  static let GRAY:  String = "0x808080"
  static let GREY:  String = "0x808080"
  static let GREEN:  String = "0x008000"
  static let GREENYELLOW:  String = "0xADFF2F"
  static let HONEYDEW:  String = "0xF0FFF0"
  static let HOTPINK:  String = "0xFF69B4"
  static let INDIANRED :  String = "0xCD5C5C"
  static let INDIGO :  String = "0x4B0082"
  static let IVORY:  String = "0xFFFFF0"
  static let KHAKI:  String = "0xF0E68C"
  static let LAVENDER:  String = "0xE6E6FA"
  static let LAVENDERBLUSH:  String = "0xFFF0F5"
  static let LAWNGREEN:  String = "0x7CFC00"
  static let LEMONCHIFFON:  String = "0xFFFACD"
  static let LIGHTBLUE:  String = "0xADD8E6"
  static let LIGHTCORAL:  String = "0xF08080"
  static let LIGHTCYAN:  String = "0xE0FFFF"
  static let LIGHTGOLDENRODYELLOW:  String = "0xFAFAD2"
  static let LIGHTGRAY:  String = "0xD3D3D3"
  static let LIGHTGREY:  String = "0xD3D3D3"
  static let LIGHTGREEN:  String = "0x90EE90"
  static let LIGHTPINK:  String = "0xFFB6C1"
  static let LIGHTSALMON:  String = "0xFFA07A"
  static let LIGHTSEAGREEN:  String = "0x20B2AA"
  static let LIGHTSKYBLUE:  String = "0x87CEFA"
  static let LIGHTSLATEGRAY:  String = "0x778899"
  static let LIGHTSLATEGREY:  String = "0x778899"
  static let LIGHTSTEELBLUE:  String = "0xB0C4DE" 
  static let LIGHTYELLOW:  String = "0xFFFFE0" 
  static let LIME:  String = "0x00FF00" 
  static let LIMEGREEN:  String = "0x32CD32" 
  static let LINEN:  String = "0xFAF0E6" 
  static let MAGENTA:  String = "0xFF00FF" 
  static let MAROON:  String = "0x800000" 
  static let MEDIUMAQUAMARINE:  String = "0x66CDAA" 
  static let MEDIUMBLUE:  String = "0x0000CD" 
  static let MEDIUMORCHID:  String = "0xBA55D3" 
  static let MEDIUMPURPLE:  String = "0x9370D8" 
  static let MEDIUMSEAGREEN:  String = "0x3CB371" 
  static let MEDIUMSLATEBLUE:  String = "0x7B68EE" 
  static let MEDIUMSPRINGGREEN:  String = "0x00FA9A" 
  static let MEDIUMTURQUOISE:  String = "0x48D1CC" 
  static let MEDIUMVIOLETRED:  String = "0xC71585" 
  static let MIDNIGHTBLUE:  String = "0x191970" 
  static let MINTCREAM:  String = "0xF5FFFA" 
  static let MISTYROSE:  String = "0xFFE4E1" 
  static let MOCCASIN:  String = "0xFFE4B5" 
  static let NAVAJOWHITE:  String = "0xFFDEAD" 
  static let NAVY:  String = "0x000080" 
  static let OLDLACE:  String = "0xFDF5E6" 
  static let OLIVE:  String = "0x808000" 
  static let OLIVEDRAB:  String = "0x6B8E23" 
  static let ORANGE:  String = "0xFFA500" 
  static let ORANGERED:  String = "0xFF4500" 
  static let ORCHID:  String = "0xDA70D6" 
  static let PALEGOLDENROD:  String = "0xEEE8AA" 
  static let PALEGREEN:  String = "0x98FB98" 
  static let PALETURQUOISE:  String = "0xAFEEEE" 
  static let PALEVIOLETRED:  String = "0xD87093" 
  static let PAPAYAWHIP:  String = "0xFFEFD5" 
  static let PEACHPUFF:  String = "0xFFDAB9" 
  static let PERU:  String = "0xCD853F" 
  static let PINK:  String = "0xFFC0CB" 
  static let PLUM:  String = "0xDDA0DD" 
  static let POWDERBLUE:  String = "0xB0E0E6" 
  static let PURPLE:  String = "0x800080" 
  static let RED:  String = "0xFF0000" 
  static let ROSYBROWN:  String = "0xBC8F8F" 
  static let ROYALBLUE:  String = "0x4169E1" 
  static let SADDLEBROWN:  String = "0x8B4513" 
  static let SALMON:  String = "0xFA8072" 
  static let SANDYBROWN:  String = "0xF4A460" 
  static let SEAGREEN:  String = "0x2E8B57" 
  static let SEASHELL:  String = "0xFFF5EE" 
  static let SIENNA:  String = "0xA0522D" 
  static let SILVER:  String = "0xC0C0C0" 
  static let SKYBLUE:  String = "0x87CEEB" 
  static let SLATEBLUE:  String = "0x6A5ACD" 
  static let SLATEGRAY:  String = "0x708090" 
  static let SLATEGREY:  String = "0x708090" 
  static let SNOW:  String = "0xFFFAFA" 
  static let SPRINGGREEN:  String = "0x00FF7F" 
  static let STEELBLUE:  String = "0x4682B4" 
  static let TAN:  String = "0xD2B48C" 
  static let TEAL:  String = "0x008080" 
  static let THISTLE:  String = "0xD8BFD8" 
  static let TOMATO:  String = "0xFF6347" 
  static let TURQUOISE:  String = "0x40E0D0" 
  static let VIOLET:  String = "0xEE82EE" 
  static let WHEAT:  String = "0xF5DEB3" 
  static let WHITE:  String = "0xFFFFFF" 
  static let WHITESMOKE:  String = "0xF5F5F5" 
  static let YELLOW:  String = "0xFFFF00" 
  static let YELLOWGREEN:  String = "0x9ACD3"
}