app: /Users/arbab/Library/Application Support/iPhone Simulator/7.0/Applications/5123C5E3-C1D7-4994-A8F8-9818983DB807/Flyr.app

devices:
  iPhone Simulator:
    default: true
    simulator: iPhone (Retina 4-inch)
    screen: retina_ios5

  iPhone 4:
    UDID: 90e16227a0c41f00b589a79db1bd8083e06fc302
    app: Flyr.app
    screen: retina_ios4

  iPhone 5:
    UDID: 3fd87224e1e01f29c3c0c84fe727865db0f66bfd
    app: Flyr.app
    screen: retina_ios5

  iPhone 5c:
    UDID: 41650836ef3786cd45c383862e5f8d4f72c04461
    app: Flyr.app
    screen: retina_ios5