app: /Users/khurram/Library/Application Support/iPhone Simulator/7.0.3/Applications/6DD6340B-FF6F-449B-BC50-EFF3D770A4B6/Flyr.app

devices:
  iPhone Simulator:
    default: true
    simulator: iPhone (Retina 4-inch)
    screen: retina_ios6

  iPhone Simulator 4:
    simulator: iPhone (Retina 3.5-inch)
    screen: retina_ios4

  iOS Device:
    UDID: 3fd87224e1e01f29c3c0c84fe727865db0f66bfd
    app: Flyr.app
    screen: retina_ios6

